[package]
name = "fshasher_own_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fshasher = { path = "../../../fshasher" }
sha2 = "0.10.8"
thiserror = "1.0.61"
