name: Checks

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  linting:
    name: Cargo Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update rust
        run: rustup update
      - name: Install nightly
        run: rustup install nightly
      - name: Add nightly toolchain
        run: rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Linting
        run: cargo +nightly clippy --all --all-features -- -D warnings
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-13, macOS-latest]
        rust: [stable]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Run tests (dev)
        run: cargo test --all-features -- --nocapture
        env:
          RUST_LOG: "debug"
          FSHASHER_STRESS_TEST_ITER_LIM: 50
      - name: Run tests (release)
        run: cargo test --all-features --release -- --nocapture
        env:
          RUST_LOG: "debug"
          FSHASHER_STRESS_TEST_ITER_LIM: 50
      - name: Check example custom_hasher
        run: cargo run
        working-directory: ./examples/custom_hasher
      - name: Check example custom_reader
        run: cargo run
        working-directory: ./examples/custom_reader
